api:
  id: "17394805"

db:
  host: "sql11.freesqldatabase.com"
  port: "3306"
  database: "sql11447598"
  username: "sql11447598"
  password: "dXalAnII9D"
  
employee_system:
  host: "1a4e-178-13-116-180.ngrok.io"
  port: "80"
  protocol: "HTTP"
  path: "/employees"